# Generated by Django 4.2.4 on 2023-08-16 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JobBoard_app', '0004_remove_candidate_user_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
